version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app  # Sync local files with container
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
