version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Serve on port 80
    volumes:
      - .:/app  # Sync local files with container
      - /app/node_modules  # Prevents overwriting node_modules
    env_file:
      - .env
